language: node_js
sudo: false
dist: trusty
before_script:
  - node script/create-test-tables.js pg://postgres@127.0.0.1:5432/postgres
env:
  - CC=clang CXX=clang++ npm_config_clang=1 PGUSER=postgres PGDATABASE=postgres

matrix:
  include:
    - node_js: "8"
      addons:
        postgresql: "9.6"
